In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/jdariasl/DiplomadoEPM_2019/master/Modulo3/init.py
from init import init; init(force_download=False)

In [1]:
import sys
if 'google.colab' in sys.modules:
    print ("setting tensorflow version in colab")
    %tensorflow_version 2.x
    %load_ext tensorboard
import tensorflow as tf
tf.__version__

'2.1.0'

In [2]:
from tensorflow.keras.layers import Embedding


In [3]:
embedding_layer = Embedding(1000, 5)


In [4]:
embedding_layer(tf.constant([1,2,3]))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 0.04910969, -0.04948508,  0.01833928, -0.00107753,  0.00912641],
       [-0.03303789, -0.00559405, -0.00318743,  0.01124633, -0.02370098],
       [-0.04715276,  0.00160822,  0.02365217, -0.02993683, -0.0436941 ]],
      dtype=float32)>

In [5]:
embedding_layer(tf.constant([[0,1,2],[3,4,5]]))

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[ 0.0258058 , -0.04209884, -0.03447083,  0.02910941,
          0.0227241 ],
        [ 0.04910969, -0.04948508,  0.01833928, -0.00107753,
          0.00912641],
        [-0.03303789, -0.00559405, -0.00318743,  0.01124633,
         -0.02370098]],

       [[-0.04715276,  0.00160822,  0.02365217, -0.02993683,
         -0.0436941 ],
        [-0.01106826,  0.04215386, -0.01418646,  0.02713865,
         -0.04123275],
        [-0.01895002, -0.0272177 ,  0.02751021,  0.01902193,
          0.00526396]]], dtype=float32)>

In [68]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import preprocessing
max_features = 100000
maxlen = 20


In [69]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features) 


In [70]:
wi = imdb.get_word_index()
iw = {v:k for k,v in wi.items()}

In [71]:
for i in range(10):
    print (i, len(x_train[i]), y_train[i], x_train[i][:20])

0 218 1 [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25]
1 189 0 [1, 194, 1153, 194, 8255, 78, 228, 5, 6, 1463, 4369, 5012, 134, 26, 4, 715, 8, 118, 1634, 14]
2 141 0 [1, 14, 47, 8, 30, 31, 7, 4, 249, 108, 7, 4, 5974, 54, 61, 369, 13, 71, 149, 14]
3 550 1 [1, 4, 18609, 16085, 33, 2804, 4, 2040, 432, 111, 153, 103, 4, 1494, 13, 70, 131, 67, 11, 61]
4 147 0 [1, 249, 1323, 7, 61, 113, 10, 10, 13, 1637, 14, 20, 56, 33, 2401, 18, 457, 88, 13, 2626]
5 43 0 [1, 778, 128, 74, 12, 630, 163, 15, 4, 1766, 7982, 1051, 43222, 32, 85, 156, 45, 40, 148, 139]
6 123 1 [1, 6740, 365, 1234, 5, 1156, 354, 11, 14, 5327, 6638, 7, 1016, 10626, 5940, 356, 44, 4, 1349, 500]
7 562 0 [1, 4, 14906, 716, 4, 65, 7, 4, 689, 4367, 6308, 2343, 4804, 28674, 84206, 5270, 32099, 2315, 71688, 12572]
8 233 1 [1, 43, 188, 46, 5, 566, 264, 51, 6, 530, 664, 14, 9, 1713, 81, 25, 1135, 46, 7, 6]
9 130 0 [1, 14, 20, 47, 111, 439, 3445, 19, 12, 15, 166, 12, 216, 125, 40, 6, 364, 352, 707,

In [73]:
for i in range(5):
    print (i, [iw[j] for j in x_train[i][:20]])

0 ['the', 'as', 'you', 'with', 'out', 'themselves', 'powerful', 'lets', 'loves', 'their', 'becomes', 'reaching', 'had', 'journalist', 'of', 'lot', 'from', 'anyone', 'to', 'have']
1 ['the', 'thought', 'solid', 'thought', 'senator', 'do', 'making', 'to', 'is', 'spot', 'nomination', 'assumed', 'while', 'he', 'of', 'jack', 'in', 'where', 'picked', 'as']
2 ['the', 'as', 'there', 'in', 'at', 'by', 'br', 'of', 'sure', 'many', 'br', 'of', 'proving', 'no', 'only', 'women', 'was', 'than', "doesn't", 'as']
3 ['the', 'of', 'bernadette', 'mon', 'they', 'halfway', 'of', 'identity', 'went', 'plot', 'actors', 'watch', 'of', 'share', 'was', 'well', 'these', 'can', 'this', 'only']
4 ['the', 'sure', 'themes', 'br', 'only', 'acting', 'i', 'i', 'was', 'favourite', 'as', 'on', 'she', 'they', 'hat', 'but', 'already', 'most', 'was', 'scares']


In [74]:
from tensorflow.keras import preprocessing


In [75]:
xx_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
xx_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

In [76]:
xx_train.shape

(25000, 20)

In [77]:
print (x_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [33]:
xx_train[0]

array([  65,   16,   38, 1334,   88,   12,   16,  283,    5,   16, 4472,
        113,  103,   32,   15,   16, 5345,   19,  178,   32], dtype=int32)

In [102]:
from tensorflow.keras.layers import Embedding, Flatten, Dense, Conv1D, MaxPooling1D
from tensorflow.keras.models import Sequential
model = Sequential()
embedding_layer = Embedding(max_features, 32, input_length=maxlen)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary() 

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 20, 32)            3200000   
_________________________________________________________________
flatten_5 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 250)               160250    
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 251       
Total params: 3,360,501
Trainable params: 3,360,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(xx_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 12s 600us/sample - loss: 0.5573 - acc: 0.6945 - val_loss: 0.4978 - val_acc: 0.7518
Epoch 2/10
20000/20000 [==============================] - 14s 679us/sample - loss: 0.3776 - acc: 0.8333 - val_loss: 0.5218 - val_acc: 0.7418
Epoch 3/10
10400/20000 [==============>...............] - ETA: 6s - loss: 0.2276 - acc: 0.9098

In [85]:
embedding_layer(10)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-0.14986037, -0.16729084, -0.01940007, -0.01645998,  0.00436411,
        0.03632338,  0.02847637, -0.04293869], dtype=float32)>

In [89]:
ecar = embedding_layer(wi["car"]).numpy()

In [91]:
etruck = embedding_layer(wi["truck"]).numpy()
ecat = embedding_layer(wi["cat"]).numpy()


In [92]:
np.linalg.norm(ecar-etruck)

0.36207294

In [93]:
np.linalg.norm(ecar-ecat)

0.6426238

In [94]:
np.linalg.norm(etruck-ecat)

0.34261662

In [98]:
# create the model
model = Sequential()
embedding_layer = Embedding(max_features, 8, input_length=maxlen)

model.add(embedding_layer)
model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 8)             800000    
_________________________________________________________________
conv1d (Conv1D)              (None, 20, 32)            800       
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 10, 32)            0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 320)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 250)               80250     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 251       
Total params: 881,301
Trainable params: 881,301
Non-trainable params: 0
________________________________________________

In [99]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(xx_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 4s 177us/sample - loss: 0.5690 - acc: 0.6852 - val_loss: 0.5033 - val_acc: 0.7374
Epoch 2/10
20000/20000 [==============================] - 3s 154us/sample - loss: 0.4342 - acc: 0.7957 - val_loss: 0.4878 - val_acc: 0.7576
Epoch 3/10
20000/20000 [==============================] - 3s 159us/sample - loss: 0.3847 - acc: 0.8274 - val_loss: 0.5038 - val_acc: 0.7564
Epoch 4/10
20000/20000 [==============================] - 3s 150us/sample - loss: 0.3501 - acc: 0.8466 - val_loss: 0.4966 - val_acc: 0.7514
Epoch 5/10
20000/20000 [==============================] - 3s 166us/sample - loss: 0.3159 - acc: 0.8645 - val_loss: 0.5417 - val_acc: 0.7496
Epoch 6/10
20000/20000 [==============================] - 4s 194us/sample - loss: 0.2794 - acc: 0.8836 - val_loss: 0.5401 - val_acc: 0.7510
Epoch 7/10
20000/20000 [==============================] - 5s 251us/sample - loss: 0.2387 - acc: 0.9018 - val_lo