# Task 01. Accuracy

Compute the percentage of correct predictions **accuracy** (see [here](https://en.wikipedia.org/wiki/Sensitivity_and_specificity#Definitions)) for the following model output (`predicted`) and ground truth (`actual`).

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
import numpy as np
t1_actual    = np.random.randint(2, size=20)
t1_predicted = np.abs(t1_actual*(np.random.random(size=20)>(np.random.random()*.9+.05)).astype(int))
print ("actual   ", ", ".join([str(i) for i in t1_actual]))
print ("predicted", ", ".join([str(i) for i in t1_predicted]))

Assign the value of your computation to the `accuracy` variable, **with three decimal places**

In [ ]:
accuracy = ...
accuracy

uncomment and execute the following lines if you want to see the solution

In [ ]:
# sol = [97, 99, 99, 117, 114, 97, 99, 121, 32, 61, 32, 110, 112, 46, 109, 101, 97, 110, 40, 116, 49, 95, 97, 99, 116, 117, 97, 108, 61, 61, 116, 49, 95, 112, 114, 101, 100, 105, 99, 116, 101, 100, 41]
# print ("".join(["%c"%i for i in sol]))


# Task 2: Sensitivity

Compute the sensitivity metric [aka the _True Positive Rate_ see [Sensitivity on Wikipedia](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)] for the following model output (`predicted`) and ground truth (`actual`)

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
import numpy as np
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]]=0
print ("actual   ", ", ".join([str(i) for i in t2_actual]))
print ("predicted", ", ".join([str(i) for i in t2_predicted]))

Assign the value of your computation to the `tpr` variable **with three decimal places**

In [ ]:
tpr =
tpr

In [ ]:
tpr

uncomment and execute the following lines if you want to see the solution

In [ ]:
# sol = [116, 112, 114, 32, 61, 32, 110, 112, 46, 109, 101, 97, 110, 40, 116, 50, 95, 97, 99, 116, 117, 97, 108, 91, 116, 50, 95, 112, 114, 101, 100, 105, 99, 116, 101, 100, 61, 61, 49, 93, 41]
# print ("".join(["%c"%i for i in sol]))


# Task 3: Evaluation in New York City Taxi Trip Duration Kaggle Competition

Understand the data and the evaluation metric (**Root Mean Squared Logarithmic Error**, RMSLE) of the following Kaggle competition

- https://www.kaggle.com/c/nyc-taxi-trip-duration/

Observe that this competition is a **regression task** as we are measuring the difference in prediction with respect to the actual.

For instance, the following model predictions and ground truth:

    actual    [66 37 22]
    predicted [79 51 67]
    
produce a **RMSLE** of 0.525 aprox.

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again

In [ ]:
t3_actual    = np.random.randint(80,size=15)+20
t3_predicted = np.random.randint(80,size=15)+20
print ("actual   ", t3_actual)
print ("predicted", t3_predicted)

Assign the value of your computation to the `rmsle` variable **with three decimal places**

In [ ]:
rmsle = ...
rmsle 

uncomment and execute the following lines if you want to see the solution

In [ ]:
# sol = [114, 109, 115, 108, 101, 32, 61, 32, 110, 112, 46, 115, 113, 114, 116, 40, 110, 112, 46, 109, 101, 97, 110, 40, 110, 112, 46, 108, 111, 103, 40, 116, 51, 95, 112, 114, 101, 100, 105, 99, 116, 101, 100, 43, 49, 41, 45, 110, 112, 46, 108, 111, 103, 40, 116, 51, 95, 97, 99, 116, 117, 97, 108, 43, 49, 41, 41, 42, 42, 50, 41]
# print ("".join(["%c"%i for i in sol]))


# Task 4: Evaluation in Shelter Animal Outcomes Kaggle Competition

Understand the data and the evaluation metric (**Multiclass Logaritmic Loss**, _logloss_) of the following Kaggle competition

- https://www.kaggle.com/c/shelter-animal-outcomes/

Observe that this competition is a **classification task with 5 classes** and, for each item, the model produces a probability for each class. Classes are numbered from 0 to 4.

For instance, the following represents the model output for **three items**

    [[0.17 0.27 0.03 0.31 0.21]
     [0.09 0.44 0.02 0.15 0.3 ]
     [0.26 0.18 0.25 0.2  0.11]]
     
Where the classes with gretest probability assigned by the model are 

- class 3 for the first item (with 0.31 probability) 
- class 1 for the second item (with 0.44 probability)
- class 0 for the third item (with 0.26 probability)

The class labels are expressed as a similar matrix, but with 0/1
For instance, the ground truth for the corresponding three items above, could be:

    [[0 0 0 1 0]
     [0 0 1 0 0]
     [1 0 0 0 0]]

and will produce a **logloss** of approx 2.14

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

In [ ]:
import numpy as np

t4_actual = np.random.random(size=(7,5)).T/4
t4_actual = np.round((t4_actual/np.sum(t4_actual,axis=0)),2).T

t4_predicted = np.eye(5)[np.random.randint(5,size=7)].astype(int)

print ("actual")
print (t4_actual)
print ("\npredicted")
print (t4_predicted)

Assign the value of your computation to the `logloss` variable **with three decimal places**

In [ ]:
losloss = 

uncomment and execute the following lines if you want to see the solution

In [ ]:
# sol = [108, 111, 103, 108, 111, 115, 115, 32, 61, 32, 45, 110, 112, 46, 109, 101, 97, 110, 40, 110, 112, 46, 108, 111, 103, 40, 110, 112, 46, 115, 117, 109, 40, 116, 52, 95, 112, 114, 101, 100, 105, 99, 116, 101, 100, 42, 116, 52, 95, 97, 99, 116, 117, 97, 108, 44, 97, 120, 105, 115, 61, 49, 41, 41, 41]
# print ("".join(["%c"%i for i in sol]))
